service: echo4

frameworkVersion: ">=1.2.0 <2.0.0"

provider:
  name: aws
  runtime: java8
  
package:
  artifact: build/libs/echo4-0.1-all.jar

functions:
  currentTime:
    handler: linebot.Handler
    events:
      - http:
          path: ping
          method: get
